server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    username: root
    password: fbb
    url: jdbc:mysql://localhost:3306/leyou
    hikari:
      max-lifetime: 28770000
      maximum-pool-size: 10
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
